run:
  timeout: 1m
  issues-exit-code: 1
  tests: true

linters-settings:
  errcheck:
    # tx.Rollback()はignoreするようにしてます。
    # 他はデフォルト値を記載
    ignore: fmt:.*,io/ioutil:^Read.*,Rollback.*

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
