version: 2.1
workflows:
  build:
    jobs:
     - build:
        filters:
         tags:
          only: /^v\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    
    working_directory: ~/warikan

    steps:
      - checkout
      - restore_cache:
          keys:
            - warikan-dep-{{ checksum "go.sum" }}
      - run:
          name : install go modules & Install GolangCI-Lint
          command: make deps
      - save_cache:
          key: warikan-dep-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: "Enforce Go Formatted Code"
          command: "! go fmt ./... 2>&1 | read"
      - run:
          name: Run GolangCI-Lint
          command: make lint
